package org.examples;


import org.junit.Test;
// Test case dependencies

public class TestsCornutum {
    // Test case declarations

    @Test
    public void postNumber_Param0Defined_Is_Yes() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postNumber_Param0Defined_Is_No() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postNumber_Param0Value_Is_Lt_m1d234() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postNumber_Param0Type_Is_Null() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postNumber_Param0Type_Is_NotNumber() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postNumber_Param0Value_Is_M1d233() {
        // Given...
        // When testServer=null...
        // Then...
    }
    // Test case closing
}
