package org.cornutum.tcases.openapi;


import org.junit.Test;
// Test case dependencies

public class ApiTests extends OpenApiTest {
    // Test case declarations

    @Test
    public void postObject_Param0Defined_Is_Yes() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0Defined_Is_No() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertyCount_Is_Leq_4() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyStringValueLength_Is_0() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyBooleanValue_Is_False() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyNumberValue_Is_Gt_0() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyIntegerValue_Is_Gt_0() {
        // Given...
        // When testServer=null...
        // Then...
    }
    // Test case closing
}
