package org.cornutum.tcases.openapi;


import org.junit.Test;
// Test case dependencies

public class ApiTests extends OpenApiTest {
    // Test case declarations

    @Test
    public void postObject_Param0Defined_Is_Yes() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0Defined_Is_No() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertyCount_Is_Leq_4() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyStringValueLength_Is_0() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyBooleanValue_Is_False() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyNumberValue_Is_Gt_0() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyIntegerValue_Is_Gt_0() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0Type_Is_Null() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0Type_Is_NotObject() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertyCount_Is_Gt_4() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyStringType_Is_Null() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyStringType_Is_NotString() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyBooleanType_Is_Null() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyBooleanType_Is_NotBoolean() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyNumberType_Is_Null() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyNumberType_Is_NotNumber() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyIntegerType_Is_Null() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void postObject_Param0ValuePropertiesMyIntegerType_Is_NotInteger() {
        // Given...
        // When testServer=null...
        // Then...
    }
    // Test case closing
}
