package org.examples;

import org.cornutum.tcases.openapi.OpenApiTest;

import org.junit.Test;
// Test case dependencies

public class Api0160JsonTest extends OpenApiTest {
    // Test case declarations

    @Test
    public void patchOperationNewRevNewOpId_0() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperationNewRevNewOpId_1() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperationNewRevNewOpId_2() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperationNewRevNewOpId_3() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperationNewRevNewOpId_4() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperationNewRevNewOpId_5() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperationNewRevNewOpId_6() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperationNewRevNewOpId_7() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperationNewRevNewOpId_8() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperations_0() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperations_1() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperations_2() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperations_3() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperations_4() {
        // Given...
        // When testServer=null...
        // Then...
    }

    @Test
    public void patchOperations_5() {
        // Given...
        // When testServer=null...
        // Then...
    }
    // Test case closing
}
