package org.cornutum.tcases.openapi;


import org.junit.Test;
// Test case dependencies

public class ApiTests extends OpenApiTest {
    // Test case declarations

    @Test
    public void putPostsPostId_0() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void putPostsPostId_1() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void putPostsPostId_2() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void putPostsPostId_3() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void putPostsPostId_4() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void putPostsPostId_5() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void putPostsPostId_6() {
        // Given...
        // When...
        // Then...
    }
    // Test case closing
}
