package org.examples;

import org.cornutum.tcases.openapi.OpenApiTest

import org.junit.Test;
// Test case dependencies

public class Api0160JsonTest extends OpenApiTest {
    // Test case declarations

    @Test
    public void getPosts_0() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPosts_1() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPosts_2() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPosts_3() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPosts_4() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPosts_5() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPosts_6() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPostsPostId_0() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPostsPostId_1() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPostsPostId_2() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPostsPostId_3() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPostsPostId_4() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPostsPostId_5() {
        // Given...
        // When...
        // Then...
    }

    @Test
    public void getPostsPostId_6() {
        // Given...
        // When...
        // Then...
    }
    // Test case closing
}
