package org.cornutum.tcases.openapi.moco;


import org.junit.Test;

import com.github.dreamhead.moco.junit.MocoJunitRunner;
import static com.github.dreamhead.moco.Moco.*;
import org.junit.ClassRule;
import com.github.dreamhead.moco.RestServer;
import static com.github.dreamhead.moco.MocoRest.*;
// Test case dependencies

public class RequestTestDef0Test {

    private static RestServer mocoServer;

    static {
        mocoServer = restServer( 12306);
    }

    @ClassRule
    public static MocoJunitRunner runner = MocoJunitRunner.restRunner( mocoServer);
    // Test case declarations

    @Test
    public void getPosts_0() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPosts_1() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPosts_2() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPosts_3() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPosts_4() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPosts_5() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPosts_6() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_0() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_1() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_2() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_3() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_4() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_5() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_6() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_7() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_8() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_9() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_10() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_11() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_12() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_13() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_14() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_15() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_16() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_17() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_18() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_19() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void postPosts_20() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void deletePostsPostId_0() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void deletePostsPostId_1() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void deletePostsPostId_2() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void deletePostsPostId_3() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void deletePostsPostId_4() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void deletePostsPostId_5() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void deletePostsPostId_6() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPostsPostId_0() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPostsPostId_1() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPostsPostId_2() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPostsPostId_3() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPostsPostId_4() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPostsPostId_5() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void getPostsPostId_6() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void patchPostsPostId_0() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void patchPostsPostId_1() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void patchPostsPostId_2() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void patchPostsPostId_3() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void patchPostsPostId_4() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void patchPostsPostId_5() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void patchPostsPostId_6() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void putPostsPostId_0() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void putPostsPostId_1() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void putPostsPostId_2() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void putPostsPostId_3() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void putPostsPostId_4() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void putPostsPostId_5() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }

    @Test
    public void putPostsPostId_6() {
        // Given...
        // When testServer=http://localhost:12306...
        // Then...
    }
    // Test case closing
}
