package org.cornutum.tcases.openapi.moco;


import org.junit.Test;

import com.github.dreamhead.moco.junit.MocoJunitRunner;
import static com.github.dreamhead.moco.Moco.*;
import org.junit.ClassRule;
import com.github.dreamhead.moco.HttpsCertificate;
import static com.github.dreamhead.moco.HttpsCertificate.certificate;
// Test case dependencies

public class RequestTestDef5Test {
    private static final HttpsCertificate myCertificate = certificate( pathResource( "myCert.cks"), "kss!", "css!");

    @ClassRule
    public static MocoJunitRunner runner = MocoJunitRunner.jsonHttpsRunner( 7777, file( "/Users/kerrykimbrough/repos/tcases/tcases-moco/target/test-classes/org/cornutum/tcases/openapi/moco/any-Moco.json"), myCertificate);
    // Test case declarations

    @Test
    public void getPosts_0() {
        // Given...
        // When testServer=http://localhost:7777...
        // Then...
    }

    @Test
    public void getPosts_1() {
        // Given...
        // When testServer=http://localhost:7777...
        // Then...
    }

    @Test
    public void getPosts_2() {
        // Given...
        // When testServer=http://localhost:7777...
        // Then...
    }

    @Test
    public void getPosts_3() {
        // Given...
        // When testServer=http://localhost:7777...
        // Then...
    }

    @Test
    public void getPosts_4() {
        // Given...
        // When testServer=http://localhost:7777...
        // Then...
    }

    @Test
    public void getPosts_5() {
        // Given...
        // When testServer=http://localhost:7777...
        // Then...
    }

    @Test
    public void getPosts_6() {
        // Given...
        // When testServer=http://localhost:7777...
        // Then...
    }
    // Test case closing
}
